version: '3.8'
services:
  db:
    image: postgres:12
    container_name: postgres_news
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ${REPOSITORY_PATH}:/docker-entrypoint-initdb.d/init.sql

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    ports:
      - "8085:8081"
    depends_on:
      - db
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
##    env_file:
##      - .env
#    depends_on:
#      - db
##    volumes:
##      - .:/root
#    environment:
#      - CONFIG_PATH=/new/app/.env
#
